# Site settings
title: Mike
email: mikekee@qq.com
description: >
  一个正在努力的Android开发者
permalink: /:year/:month/:day/:title/
baseurl: "" 
url: "http://hi-mike.github.io"
twitter_username: 
github_username: Hi-Mike

# Build settings
markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]